- name: Automated Ubuntu post-installation
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: user_account
      tags: [user_account]
    - role: system
      tags: [system]
    - role: dev_tools
      tags: [dev_tools]
    - role: php
      tags: [php]
    - role: desktop
      tags: [desktop]
    - role: kiro
      tags: [kiro]
    - role: workspace
      tags: [workspace]
